In [1]:
import pandas as pd
orders_df = pd.read_csv('Day9_Orders.csv')
customers_df = pd.read_csv('Day9_Customers.csv')
products_df = pd.read_csv('Day9_Products.csv')
print("Orders Dataset:")
display(orders_df.head(2))
print("\nCustomers Dataset:")
display(customers_df.head(2))
print("\nProducts Dataset:")
display(products_df.head(2))

Orders Dataset:

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered

Customers Dataset:

  Customer_ID Customer_Name      City Region Membership_Type
0        C001  Aarav Sharma  Srinagar  North         Premium
1        C002     Zoya Khan     Delhi  North         Regular

Products Dataset:

  Product_ID         Product_Name     Category  Unit_Price     Brand
0       P001  Wireless Headphones  Electronics        1499  SoundMax
1       P002  Mechanical Keyboard  Electronics        2499    KeyPro

In [2]:
merged_df = orders_df.merge(customers_df, on='Customer_ID', how='left')
final_merged_df = merged_df.merge(products_df, on='Product_ID', how='left')
print("Data after merging:")
display(final_merged_df.head())

Data after merging:

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew

In [3]:
final_merged_df['Order_Date'] = pd.to_datetime(final_merged_df['Order_Date'])
final_merged_df['Order_Month'] = final_merged_df['Order_Date'].dt.month_name()
final_merged_df['Order_Day'] = final_merged_df['Order_Date'].dt.day
final_merged_df['Order_Day_of_Week'] = final_merged_df['Order_Date'].dt.day_name()
print("Data with DateTime features:")
display(final_merged_df[['Order_ID', 'Order_Date', 'Order_Month', 'Order_Day', 'Order_Day_of_Week']].head())

Data with DateTime features:

  Order_ID Order_Date Order_Month  Order_Day Order_Day_of_Week
0    O0001 2026-02-19    February         19          Thursday
1    O0002 2026-01-25     January         25            Sunday
2    O0003 2026-02-26    February         26          Thursday
3    O0004 2026-03-04       March          4         Wednesday
4    O0005 2026-03-29       March         29            Sunday

In [4]:
final_merged_df['Total_Amount'] = final_merged_df.apply(
    lambda row: row['Quantity'] * row['Unit_Price'] if pd.notnull(row['Unit_Price']) else 0,
    axis=1
)
final_merged_df['Priority_Shipping'] = final_merged_df['Membership_Type'].apply(
    lambda x: 'Yes' if x == 'Premium' else 'No'
)
print("Data after apply() transformations:")
display(final_merged_df[['Order_ID', 'Quantity', 'Unit_Price', 'Total_Amount', 'Membership_Type', 'Priority_Shipping']].head())

Data after apply() transformations:

,Order_ID,Quantity,Unit_Price,Total_Amount,Membership_Type,Priority_Shipping
0,O0001,2,2499,4998,Premium,Yes
1,O0002,2,899,1798,Premium,Yes
2,O0003,1,3299,3299,Regular,No
3,O0004,3,999,2997,Regular,No
4,O0005,5,3499,17495,New,No

In [5]:
north_region = final_merged_df[final_merged_df['Region'] == 'North']
south_region = final_merged_df[final_merged_df['Region'] == 'South']
recombined_df = pd.concat([north_region, south_region], axis=0, ignore_index=True)
print("Demonstrating concat() - Recombined DataFrame length:", len(recombined_df))
display(recombined_df.head())

Demonstrating concat() - Recombined DataFrame length: 90

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand,Order_Month,Order_Day,Order_Day_of_Week,Total_Amount,Priority_Shipping
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro,February,19,Thursday,4998,Yes
1,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech,February,26,Thursday,3299,No
2,O0007,2026-02-10,C011,P003,3,UPI,Delivered,Vivaan Kapoor,Jaipur,North,New,Wireless Mouse,Electronics,899,TechGear,February,10,Tuesday,2697,No
3,O0010,2026-03-05,C026,P005,2,Debit Card,Shipped,Fatima Noor,Srinagar,North,Regular,Power Bank,Electronics,1199,VoltPlus,March,5,Thursday,2398,No
4,O0013,2026-03-22,C005,P009,3,Cash on Delivery,Delivered,Kabir Ali,Lucknow,North,New,Coffee Maker,Home & Kitchen,3499,HomeBrew,March,22,Sunday,10497,No

In [6]:
processed_dataset = recombined_df.sort_values(by='Order_Date', ascending=True).reset_index(drop=True)
output_filename = 'Processed_Ecommerce_Dataset.csv'
processed_dataset.to_csv(output_filename, index=False)
print(f"Success! The processed dataset has been exported as '{output_filename}'.")

Success! The processed dataset has been exported as 'Processed_Ecommerce_Dataset.csv'.